// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA81xdrUnOmL6LZ4II76cFOxSZfoh3JxKo',
    appId: '1:103013656875:web:d29e23db69a14ef4f13d6e',
    messagingSenderId: '103013656875',
    projectId: 'task-management-app-2711e',
    authDomain: 'task-management-app-2711e.firebaseapp.com',
    storageBucket: 'task-management-app-2711e.appspot.com',
    measurementId: 'G-5KWCFXW6EL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0eVMTgdLtWVTOKiqUFqwveGMi7wqY8ls',
    appId: '1:103013656875:android:115d7d9f78730270f13d6e',
    messagingSenderId: '103013656875',
    projectId: 'task-management-app-2711e',
    storageBucket: 'task-management-app-2711e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfYElFPMcM7glvGmlYFlOR4gaUxy_f6fw',
    appId: '1:103013656875:ios:10ca3eaf5206b7e8f13d6e',
    messagingSenderId: '103013656875',
    projectId: 'task-management-app-2711e',
    storageBucket: 'task-management-app-2711e.appspot.com',
    androidClientId:
        '103013656875-9irqnupfgr6nikqt9k1l96vd2je0m7dg.apps.googleusercontent.com',
    iosClientId:
        '103013656875-m7bo58qb89u43iceflg3epss2pkj5jce.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfYElFPMcM7glvGmlYFlOR4gaUxy_f6fw',
    appId: '1:103013656875:ios:10ca3eaf5206b7e8f13d6e',
    messagingSenderId: '103013656875',
    projectId: 'task-management-app-2711e',
    storageBucket: 'task-management-app-2711e.appspot.com',
    androidClientId:
        '103013656875-9irqnupfgr6nikqt9k1l96vd2je0m7dg.apps.googleusercontent.com',
    iosClientId:
        '103013656875-m7bo58qb89u43iceflg3epss2pkj5jce.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManagementApp',
  );
}
